# Generated by Django 5.2.16 on 2026-07-11 01:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='senha_hash', max_length=255, verbose_name='senha')),
                ('tipo_usuario', models.CharField(choices=[('comum', 'Comum'), ('admin', 'Administrador')], default='comum', max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('perfil_publico', models.BooleanField(default=True)),
                ('steam_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'usuário',
                'db_table': 'users',
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo_usuario__in', ('comum', 'admin'))), name='ck_users_tipo_usuario')],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
