# Generated by Django 5.2.16 on 2026-07-13 12:16

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_updated_at_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.avatar_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='avatar'),
        ),
    ]
