# Generated by Django 5.2.16 on 2026-07-11 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'desenvolvedora',
                'db_table': 'developers',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'gênero',
                'db_table': 'genres',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'plataforma',
                'db_table': 'platforms',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'publicadora',
                'db_table': 'publishers',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('capa_url', models.URLField(blank=True, max_length=500, null=True)),
                ('banner_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ano_lancamento', models.IntegerField(blank=True, null=True)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('status_publicacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=20)),
                ('steam_appid', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developers', models.ManyToManyField(blank=True, db_table='game_developers', related_name='games', to='catalog.developer')),
                ('genres', models.ManyToManyField(blank=True, db_table='game_genres', related_name='games', to='catalog.genre')),
                ('platforms', models.ManyToManyField(blank=True, db_table='game_platforms', related_name='games', to='catalog.platform')),
                ('publishers', models.ManyToManyField(blank=True, db_table='game_publishers', related_name='games', to='catalog.publisher')),
            ],
            options={
                'verbose_name': 'jogo',
                'db_table': 'games',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_apiname', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='catalog.game')),
            ],
            options={
                'verbose_name': 'conquista',
                'db_table': 'achievements',
                'constraints': [models.UniqueConstraint(fields=('game', 'steam_apiname'), name='uq_game_achievement')],
            },
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('status_publicacao__in', ('rascunho', 'publicado'))), name='ck_games_status_publicacao'),
        ),
    ]
