# Generated by Django 5.2.16 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_updated_at_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
