# Generated by Django 5.2.16 on 2026-07-11 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_recebidas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'amizade',
                'db_table': 'friendships',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('publica', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lista customizada',
                'db_table': 'lists',
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('pk', models.CompositePrimaryKey('lista_id', 'game_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='list_items', to='catalog.game')),
                ('lista', models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='social.list')),
            ],
            options={
                'verbose_name': 'item de lista',
                'verbose_name_plural': 'itens de lista',
                'db_table': 'list_items',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido_amizade', 'Pedido de amizade'), ('amizade_aceita', 'Amizade aceita'), ('review_curtida', 'Review curtida')], max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_geradas', to=settings.AUTH_USER_MODEL)),
                ('friendship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.friendship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('user_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='library.usergame')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('pk', models.CompositePrimaryKey('user_game_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to=settings.AUTH_USER_MODEL)),
                ('user_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='library.usergame')),
            ],
            options={
                'verbose_name': 'curtida de review',
                'verbose_name_plural': 'curtidas de review',
                'db_table': 'review_likes',
            },
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='uq_friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pendente', 'aceito'))), name='ck_friendships_status'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='ck_friendship_nao_reflexiva'),
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('user', 'nome'), name='uq_list_user_nome'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'lida'], name='idx_notifications_user_lida'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ('pedido_amizade', 'amizade_aceita', 'review_curtida'))), name='ck_notifications_tipo'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('friendship__isnull', False), ('tipo__in', ('pedido_amizade', 'amizade_aceita')), ('user_game__isnull', True)), models.Q(('friendship__isnull', True), ('tipo', 'review_curtida'), ('user_game__isnull', False)), _connector='OR'), name='ck_notifications_referencia'),
        ),
    ]
